server:
  port: 7000

app:
  book-service:
    host: localhost
    port: 7001
  rating-service:
    host: localhost
    port: 7002
  review-service:
    host: localhost
    port: 7003
    
---
spring.config.activate.on-profile: docker

server:
  port: 8080

app:
  book-service:
    host: book
    port: 8080
  rating-service:
    host: rating
    port: 8080
  review-service:
    host: review
    port: 8080